Repository epam/edp-nexus-operator, pull requests merged in 2024-08, with the labels that each got.

#38 chore: Update KubeRocketCI names and documentation links (#37)
  .github/workflows/release.yaml
  README.md
  deploy-templates/Chart.yaml
  deploy-templates/README.md
  deploy-templates/README.md.gotmpl
  deploy-templates/values.yaml
Labels: enhancement

#41 docs: Fix README.md
  README.md
  deploy-templates/README.md
  deploy-templates/README.md.gotmpl
Labels: bug

#40 docs: Fix broken format in README md (#39)
  README.md
Labels: documentation
